exports.globalLexicon = {
  "let" : { "tk": 0x12, "cls": "keyword" },
  "if" : { "tk": 0x05, "cls": "keyword" },
  "then" : { "tk": 0x06, "cls": "keyword" },
  "else" : { "tk": 0x07, "cls": "keyword" },
  "case" : { "tk": 0x0F, "cls": "keyword" },
  "of" : { "tk": 0x10, "cls": "keyword" },
  "end" : { "tk": 0x11, "cls": "keyword", "length": 0 },
  
  "true" : { "tk": 0x14, "cls": "val", "length": 0 },
  "false" : { "tk": 0x14, "cls": "val", "length": 0 },
  
  // functions
  "add" : { "tk": 0x01, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 0x01, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "grid" : { "tk": 0x01, "name": "GRID", "cls": "function", "length": 1, "arity": 1 },
  "row" : { "tk": 0x01, "name": "ROW", "cls": "function", "length": 1, "arity": 1 },
  "one-column" : { "tk": 0x01, "name": "ONE-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "two-columns" : { "tk": 0x01, "name": "TWO-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "three-columns" : { "tk": 0x01, "name": "THREE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "four-columns" : { "tk": 0x01, "name": "FOUR-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "five-columns" : { "tk": 0x01, "name": "FIVE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "six-columns" : { "tk": 0x01, "name": "SIX-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "seven-columns" : { "tk": 0x01, "name": "SEVEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "eight-columns" : { "tk": 0x01, "name": "EIGHT-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "nine-columns" : { "tk": 0x01, "name": "NINE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "ten-columns" : { "tk": 0x01, "name": "TEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "eleven-columns" : { "tk": 0x01, "name": "ELEVEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "twelve-columns" : { "tk": 0x01, "name": "TWELVE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "one-third-column" : { "tk": 0x01, "name": "ONE-THIRD-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "two-thirds-column" : { "tk": 0x01, "name": "TWO-THIRDS-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "one-half-column" : { "tk": 0x01, "name": "ONE-HALF-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "h1" : { "tk": 0x01, "name": "H1", "cls": "function", "length": 1, "arity": 1 },
  "h2" : { "tk": 0x01, "name": "H2", "cls": "function", "length": 1, "arity": 1 },
  "h3" : { "tk": 0x01, "name": "H3", "cls": "function", "length": 1, "arity": 1 },
  "h4" : { "tk": 0x01, "name": "H4", "cls": "function", "length": 1, "arity": 1 },
  "h5" : { "tk": 0x01, "name": "H5", "cls": "function", "length": 1, "arity": 1 },
  "h6" : { "tk": 0x01, "name": "H6", "cls": "function", "length": 1, "arity": 1 },
  "code" : { "tk": 0x01, "name": "CODE", "cls": "function", "length": 1, "arity": 1 },
  "cspan" : { "tk": 0x01, "name": "CSPAN", "cls": "function", "length": 1, "arity": 1 },
  "button" : { "tk": 0x01, "name": "BUTTON", "cls": "function", "length": 1, "arity": 1 },
  "primary-button" : { "tk": 0x01, "name": "PRIMARY-BUTTON", "cls": "function", "length": 1, "arity": 1 },
  "href" : { "tk": 0x01, "name": "HREF", "cls": "function", "length": 2, "arity": 2 },
  "id" : { "tk": 0x01, "name": "ID", "cls": "function", "length": 2, "arity": 2 },

  "table" : { "tk": 0x01, "name": "TABLE", "cls": "function", "length": 1, "arity": 1 },
  "thead" : { "tk": 0x01, "name": "THEAD", "cls": "function", "length": 1, "arity": 1 },
  "tbody" : { "tk": 0x01, "name": "TBODY", "cls": "function", "length": 1, "arity": 1 },
  "th" : { "tk": 0x01, "name": "TH", "cls": "function", "length": 1, "arity": 1 },
  "tr" : { "tk": 0x01, "name": "TR", "cls": "function", "length": 1, "arity": 1 },
  "td" : { "tk": 0x01, "name": "TD", "cls": "function", "length": 1, "arity": 1 },
  "ul" : { "tk": 0x01, "name": "UL", "cls": "function", "length": 1, "arity": 1 },
  "ol" : { "tk": 0x01, "name": "OL", "cls": "function", "length": 1, "arity": 1 },
  "li" : { "tk": 0x01, "name": "LI", "cls": "function", "length": 1, "arity": 1 },
  "img" : { "tk": 0x01, "name": "IMG", "cls": "function", "length": 1, "arity": 1 },
  "graffito" : { "tk": 0x01, "name": "GRAFFITO", "cls": "function", "length": 1, "arity": 1 },

  // values
  "timer" : { "tk": 0x01, "cls": "string", "val": "$$timer$$", "length": 0 },
  "prose" : { "tk": 0x01, "cls": "string", "val": "$$prose$$", "length": 0 },
};
