window.gcexports.globalLexicon = {
  "let" : { "tk": 18, "cls": "keyword" },
  "if" : { "tk": 5, "cls": "keyword" },
  "then" : { "tk": 6, "cls": "keyword" },
  "else" : { "tk": 7, "cls": "keyword" },
  "case" : { "tk": 15, "cls": "keyword" },
  "of" : { "tk": 16, "cls": "keyword" },
  "end" : { "tk": 17, "cls": "keyword", "length": 0 },
  "true" : { "tk": 20, "cls": "val", "length": 0 },
  "false" : { "tk": 200, "cls": "val", "length": 0 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "grid" : { "tk": 1, "name": "GRID", "cls": "function", "length": 1, "arity": 1 },
  "grid-left" : { "tk": 1, "name": "GRID-LEFT", "cls": "function", "length": 1, "arity": 1 },
  "row" : { "tk": 1, "name": "ROW", "cls": "function", "length": 1, "arity": 1 },
  "one-column" : { "tk": 1, "name": "ONE-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "two-columns" : { "tk": 1, "name": "TWO-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "three-columns" : { "tk": 1, "name": "THREE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "four-columns" : { "tk": 1, "name": "FOUR-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "five-columns" : { "tk": 1, "name": "FIVE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "six-columns" : { "tk": 1, "name": "SIX-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "seven-columns" : { "tk": 1, "name": "SEVEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "eight-columns" : { "tk": 1, "name": "EIGHT-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "nine-columns" : { "tk": 1, "name": "NINE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "ten-columns" : { "tk": 1, "name": "TEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "eleven-columns" : { "tk": 1, "name": "ELEVEN-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "twelve-columns" : { "tk": 1, "name": "TWELVE-COLUMNS", "cls": "function", "length": 1, "arity": 1 },
  "one-third-column" : { "tk": 1, "name": "ONE-THIRD-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "two-thirds-column" : { "tk": 1, "name": "TWO-THIRDS-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "one-half-column" : { "tk": 1, "name": "ONE-HALF-COLUMN", "cls": "function", "length": 1, "arity": 1 },
  "h1" : { "tk": 1, "name": "H1", "cls": "function", "length": 1, "arity": 1 },
  "h2" : { "tk": 1, "name": "H2", "cls": "function", "length": 1, "arity": 1 },
  "h3" : { "tk": 1, "name": "H3", "cls": "function", "length": 1, "arity": 1 },
  "h4" : { "tk": 1, "name": "H4", "cls": "function", "length": 1, "arity": 1 },
  "h5" : { "tk": 1, "name": "H5", "cls": "function", "length": 1, "arity": 1 },
  "h6" : { "tk": 1, "name": "H6", "cls": "function", "length": 1, "arity": 1 },
  "br" : { "tk": 1, "name": "BR", "cls": "function", "length": 0, "arity": 0 },
  "code" : { "tk": 1, "name": "CODE", "cls": "function", "length": 1, "arity": 1 },
  "cspan" : { "tk": 1, "name": "CSPAN", "cls": "function", "length": 1, "arity": 1 },
  "textarea" : { "tk": 1, "name": "TEXTAREA", "cls": "function", "length": 1, "arity": 1 },
  "button" : { "tk": 1, "name": "BUTTON", "cls": "function", "length": 1, "arity": 1 },
  "primary-button" : { "tk": 1, "name": "PRIMARY-BUTTON", "cls": "function", "length": 1, "arity": 1 },
  "href" : { "tk": 1, "name": "HREF", "cls": "function", "length": 2, "arity": 2 },
  "id" : { "tk": 1, "name": "ID", "cls": "function", "length": 2, "arity": 2 },

  "table" : { "tk": 1, "name": "TABLE", "cls": "function", "length": 1, "arity": 1 },
  "thead" : { "tk": 1, "name": "THEAD", "cls": "function", "length": 1, "arity": 1 },
  "tbody" : { "tk": 1, "name": "TBODY", "cls": "function", "length": 1, "arity": 1 },
  "th" : { "tk": 1, "name": "TH", "cls": "function", "length": 1, "arity": 1 },
  "tr" : { "tk": 1, "name": "TR", "cls": "function", "length": 1, "arity": 1 },
  "td" : { "tk": 1, "name": "TD", "cls": "function", "length": 1, "arity": 1 },
  "ul" : { "tk": 1, "name": "UL", "cls": "function", "length": 1, "arity": 1 },
  "ol" : { "tk": 1, "name": "OL", "cls": "function", "length": 1, "arity": 1 },
  "li" : { "tk": 1, "name": "LI", "cls": "function", "length": 1, "arity": 1 },
  "img" : { "tk": 1, "name": "IMG", "cls": "function", "length": 1, "arity": 1 },
  "graffito" : { "tk": 1, "name": "GRAFFITO", "cls": "function", "length": 1, "arity": 1 },
  "title" : { "tk": 1, "name": "TITLE", "cls": "function", "length": 1, "arity": 1 },
  "timer" : { "tk": 1, "cls": "string", "val": "$$timer$$", "length": 0 },
  "prose" : { "tk": 1, "cls": "string", "val": "$$prose$$", "length": 0 }
}
